name: Tests

on:
  push:
  pull_request:
  release:
  schedule:
    # Every Thursday at 1 AM
    - cron: '0 1 * * 4'

jobs:

  Tests:
    continue-on-error: ${{ matrix.optional || false }}
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    name: >-
      ${{ matrix.nox-session }}
      (${{ matrix.python-version }})
      ${{ matrix.optional && '[OPTIONAL]' }}

    strategy:
      fail-fast: false

      matrix:
        python-version: ['3.11']
        nox-session: [pylint, flake8]

    env:
      NOXSESSION: ${{ matrix.nox-session }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Nox
        run: pip install nox tomli

      - name: Run Nox
        run: nox -v