name: Tests

on:
  push:
  pull_request:
  release:
  schedule:
    # Every Thursday at 1 AM
    - cron: '0 1 * * 4'

jobs:

  Tests:
    continue-on-error: ${{ matrix.optional || false }}
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    name: >-
      ${{ matrix.nox-session }}
      (${{ matrix.python-version }})
      ${{ matrix.optional && '[OPTIONAL]' }}

    strategy:
      fail-fast: false

      matrix:
        python-version: ['3.11']
        nox-session: [coverage, flake8, pylint, readme]
        include:

          - python-version: '3.7'
            nox-session: test

          - python-version: '3.8'
            nox-session: test

          - python-version: '3.9'
            nox-session: test

          - python-version: '3.10'
            nox-session: test

          - python-version: '3.12-dev'
            nox-session: test
            nox-python: '3.12'
            optional: true

    env:
      NOXSESSION: ${{ matrix.nox-session }}
      NOXPYTHON: ${{ matrix.nox-python || matrix.python-version }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Nox
        run: pip install nox tomli

      - name: Run Nox
        run: nox -v --force-python $NOXPYTHON
